#!/usr/bin/env python3
"""
towit_setup — Initialize the To Wit catalog database.

Usage:
    python3 towit_setup.py [--config] [--full] [--hook]
"""

import argparse
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from towit_config import config, CONFIG_PATH
from towit_db import Database

_CONFIG_TEMPLATE = """\
# To Wit configuration
# https://github.com/chrisbloom7/to-wit
#
# Generated by: towit setup --config
# Edit this file to customize To Wit's behavior.

[database]
# Database file path. Default: ~/.towit/catalog.db
# path = "~/.towit/catalog.db"
"""


def generate_config():
    """Write a starter config.toml. Does nothing if file already exists."""
    config_path = os.path.expanduser(CONFIG_PATH)
    if os.path.isfile(config_path):
        print(f"Config file already exists at {config_path}")
        return
    parent = os.path.dirname(config_path)
    os.makedirs(parent, exist_ok=True)
    old_umask = os.umask(0o177)  # 0600 permissions
    try:
        with open(config_path, 'w') as f:
            f.write(_CONFIG_TEMPLATE)
    finally:
        os.umask(old_umask)
    print(f"Config file created at {config_path}")


def main():
    parser = argparse.ArgumentParser(
        description='Initialize the To Wit catalog database.'
    )
    parser.add_argument('--config', action='store_true',
                        help='Generate a starter config.toml')
    parser.add_argument('--full', action='store_true',
                        help='Also generate config, install hook, and run backfill')
    parser.add_argument('--hook', action='store_true',
                        help='Also install the stop hook after setup')
    args = parser.parse_args()

    if args.full or args.config:
        generate_config()

    db_path = config.db_path
    db = Database(db_path)

    if os.path.isfile(db_path):
        db.run_migrations()
        print(f"Database already initialized at {db_path}")
        if not (args.full or args.hook):
            sys.exit(0)
    else:
        parent = os.path.dirname(db_path)
        old_umask = os.umask(0o077)
        try:
            os.makedirs(parent, exist_ok=True)
            db.create_schema()
        finally:
            os.umask(old_umask)
        print(f"Database initialized at {db_path}")

    if args.full or args.hook:
        from towit_install_hook import main as install_hook
        install_hook()

    if args.full:
        from towit_backfill import main as backfill
        backfill()


if __name__ == '__main__':
    main()
