#!/usr/bin/env python3
"""
towit_setup — Initialize the To Wit catalog database.

Usage:
    python3 towit_setup.py [--config] [--full] [--hook]
"""

import argparse
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from towit_config import config, CONFIG_PATH
from towit_db import Database

_CONFIG_TEMPLATE = """\
# To Wit configuration
# https://github.com/chrisbloom7/to-wit
#
# Generated by: towit setup --config
# Edit this file to customize To Wit's behavior.

[database]
# Database file path. Default: ~/.towit/catalog.db
# path = "~/.towit/catalog.db"

[indexing]
# Model used for analysis. Use "default" to inherit your Claude Code default model,
# or any alias ("sonnet", "opus") or full model ID ("claude-sonnet-4-6").
# Haiku is fast and inexpensive; Sonnet/Opus are more capable but cost significantly more.
# Default: "haiku"
# model = "haiku"

# How many exchanges (user + assistant pairs) must occur before a resumed session
# is re-analyzed. The stop hook fires after every response; this prevents unnecessary
# API calls mid-conversation. Set to 1 to re-analyze after every exchange.
# Default: 2
# reindex_delta = 2

# Range of topic tags Claude should assign per conversation (min must be <= max).
# Default: 1–5
# min_topics = 1
# max_topics = 5

# Range of keywords Claude should extract per conversation (min must be <= max).
# Default: 15–30
# min_keywords = 15
# max_keywords = 30

# Range of sentences for the generated summary (min must be <= max).
# Default: 3–6
# min_summary_sentences = 3
# max_summary_sentences = 6

# Maximum characters of transcript text sent to Claude for analysis.
# Longer transcripts cost more; the excerpt always keeps the first 30% and last 70%.
# Default: 8000
# transcript_max_chars = 8000
"""


def generate_config():
    """Write a starter config.toml. Does nothing if file already exists."""
    config_path = os.path.expanduser(CONFIG_PATH)
    if os.path.isfile(config_path):
        print(f"Config file already exists at {config_path}")
        return
    parent = os.path.dirname(config_path)
    os.makedirs(parent, exist_ok=True)
    old_umask = os.umask(0o177)  # 0600 permissions
    try:
        with open(config_path, 'w') as f:
            f.write(_CONFIG_TEMPLATE)
    finally:
        os.umask(old_umask)
    print(f"Config file created at {config_path}")


def main():
    parser = argparse.ArgumentParser(
        description='Initialize the To Wit catalog database.'
    )
    parser.add_argument('--config', action='store_true',
                        help='Generate a starter config.toml')
    parser.add_argument('--full', action='store_true',
                        help='Also generate config, install hook, and run backfill')
    parser.add_argument('--hook', action='store_true',
                        help='Also install the stop hook after setup')
    args = parser.parse_args()

    if args.full or args.config:
        generate_config()

    db_path = config.db_path
    db = Database(db_path)

    if os.path.isfile(db_path):
        db.run_migrations()
        print(f"Database already initialized at {db_path}")
        if not (args.full or args.hook):
            sys.exit(0)
    else:
        parent = os.path.dirname(db_path)
        old_umask = os.umask(0o077)
        try:
            os.makedirs(parent, exist_ok=True)
            db.create_schema()
        finally:
            os.umask(old_umask)
        print(f"Database initialized at {db_path}")

    if args.full or args.hook:
        from towit_install_hook import main as install_hook
        install_hook()

    if args.full:
        from towit_backfill import main as backfill
        backfill()


if __name__ == '__main__':
    main()
